# Generated by Django 5.0.4 on 2024-06-25 13:12

from django.db import migrations


def set_rarity_for_price(apps, schema_editor):
    item_model = apps.get_model('main_app', 'Item')
    all_items = item_model.objects.all()

    for item in all_items:
        if item.price <= 10:
            item.rarity = 'Rare'

        elif 11 <= item.price <= 20:
            item.rarity = 'Very Rare'

        elif 21 <= item.price <= 30:
            item.rarity = 'Extremely Rare'

        else:
            item.rarity = 'Mega Rare'

    item_model.objects.bulk_update(all_items, ['rarity'])


def reverse_rarity_for_price(apps, schema_editor):
    item_model = apps.get_model('main_app', 'Item')
    for item in item_model.objects.all():
        item.rarity = item_model._meta.get_field('rarity').default
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_item'),
    ]

    operations = [migrations.RunPython(set_rarity_for_price, reverse_rarity_for_price)]
