# Generated by Django 5.0.4 on 2024-06-26 09:03

from django.db import migrations


def generate_new_price(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')
    all_smartphones = smartphone_model.objects.all()

    for smartphone in all_smartphones:
        smartphone.price = 120 * len(smartphone.brand)

    smartphone_model.objects.bulk_update(all_smartphones, ['price'])


def generate_new_category(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')
    all_smartphones = smartphone_model.objects.all()

    for smartphone in all_smartphones:
        if smartphone.price >= 750:
            smartphone.category = 'Expensive'
        else:
            smartphone.category = 'Cheap'

        smartphone.save()


def reverse_price_and_category_values(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')
    all_smartphones = smartphone_model.objects.all()

    for smartphone in all_smartphones:
        smartphone.category = smartphone_model._meta.get_field('category').default
        smartphone.price = smartphone_model._meta.get_field('price').default
        smartphone.save()


def call_functions(apps, schema_editor):
    generate_new_price(apps, schema_editor)
    generate_new_category(apps, schema_editor)


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_smartphone'),
    ]

    operations = [migrations.RunPython(call_functions, reverse_price_and_category_values)]
